### ISSUE TITLE
.NET 5.0 + Kestrel: InvalidOperationException: ApplicationServices must not be null. This is normally set automatically via IConfigureOptions

### ISSUE THREAD

**Issue by Kobus-Smit** [ngs-doo/revenj#162]
Hi

* I've created a simpler version [AspNetTutorialLite](https://github.com/Kobus-Smit/revenj-examples/tree/master/DotNetCore/netcoreapp2.1/AspNetTutorialLite) of the [AspNetCore tutorial](https://github.com/ngs-doo/revenj/tree/master/tutorials/AspNetCore) 

* Got it working against .NET Core 3.1 with `IWebHostBuilder` because [`'IHostBuilder' does not contain a definition for 'UseRevenj' and the best extension method overload 'RevenjWebHostBuilderExtension.UseRevenj(IWebHostBuilder)' requires a receiver of type 'IWebHostBuilder'`](https://github.com/Kobus-Smit/revenj-examples/blob/58cc393c79685f21a423150c1db22e140160b777/DotNetCore/netcoreapp3.1/AspNetTutorialLite/Program.cs#L18)

* This .NET Core 3.1 example works fine when launched in IIS or Kestrel 🎉

* Then [only line](https://github.com/Kobus-Smit/revenj-examples/blob/58cc393c79685f21a423150c1db22e140160b777/DotNetCore/net5.0/AspNetTutorialLite/AspNetTutorial.csproj#L4
) changed, and it ran fine on .NET 5 and IIS 🎉
 
* but not on Kestrel anymore

```
Revenj.Extensibility.Autofac.Core.DependencyResolutionException
  HResult=0x80131500
  Message=An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Options.IOptions`1[Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions], System.Collections.Generic.IEnumerable`1[Microsoft.AspNetCore.Connections.IConnectionListenerFactory], System.Collections.Generic.IEnumerable`1[Microsoft.AspNetCore.Connections.Experimental.IMultiplexedConnectionListenerFactory], Microsoft.Extensions.Logging.ILoggerFactory)' on type 'KestrelServerImpl'.
Dependency path: 
  Source=Revenj.Core
  StackTrace:
   at Revenj.Extensibility.Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Revenj.Extensibility.Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass8_0.<GetFactory>b__1()
   at Revenj.Extensibility.Autofac.Core.Resolving.InstanceLookup.<>c__DisplayClass23_0.<Activate>b__0()
   at Revenj.Extensibility.Autofac.Core.Resolving.InstanceLookup.<>c__DisplayClass22_0.<Prepare>b__0()
   at Revenj.Extensibility.Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Revenj.Extensibility.Autofac.Core.Resolving.InstanceLookup.Prepare(IEnumerable`1 parameters)
   at Revenj.Extensibility.Autofac.Core.Resolving.InstanceLookup.get_Factory()
   at Revenj.Extensibility.AutofacObjectFactory.GetFactory(Type type)
   at Revenj.Extensibility.AutofacObjectFactory.GetService(Type type)
   at Revenj.AspNetCore.AspNetContainer.GetService(Type serviceType)
   at Revenj.AspNetCore.AspNetContainer.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureServer()
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHost.<StartAsync>d__27.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at AspNetTutorial.Program.Main(String[] args) in C:\Dev\OpenSource\revenj-examples\DotNetCore\net5.0\AspNetTutorialLite\Program.cs:line 12

  This exception was originally thrown at this call stack:
    Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Configure(Microsoft.Extensions.Configuration.IConfiguration, bool)
    Microsoft.AspNetCore.WebHost.ConfigureWebDefaults.AnonymousMethod__9_1(Microsoft.AspNetCore.Hosting.WebHostBuilderContext, Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions)
    Microsoft.AspNetCore.Hosting.WebHostBuilderKestrelExtensions.ConfigureKestrel.AnonymousMethod__1(Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions)
    Microsoft.Extensions.Options.ConfigureNamedOptions<TOptions>.Configure(string, TOptions)
    Microsoft.Extensions.Options.OptionsFactory<TOptions>.Create(string)
    Microsoft.Extensions.Options.OptionsManager<TOptions>.Get.AnonymousMethod__0()
    System.Lazy<T>.ViaFactory(System.Threading.LazyThreadSafetyMode)
    System.Lazy<T>.ExecutionAndPublication(System.LazyHelper, bool)
    System.Lazy<T>.CreateValue()
    System.Lazy<T>.Value.get()
    ...
    [Call Stack Truncated]

Inner Exception 1:
InvalidOperationException: ApplicationServices must not be null. This is normally set automatically via IConfigureOptions.

```

Repo:
https://github.com/Kobus-Smit/revenj-examples/tree/master/DotNetCore/net5.0/AspNetTutorialLite

![image](https://user-images.githubusercontent.com/11263864/129465445-e95b61c5-06a4-4337-ab67-2e39d9d051ac.png)

**Comment by zapov** [comment]
Nuget package is up: https://www.nuget.org/packages/Revenj.AspNetCore/

**Comment by Kobus-Smit** [comment]
Resolved after updating [AspNetTutorialLite](https://github.com/Kobus-Smit/revenj-examples/tree/master/DotNetCore/net5.0/AspNetTutorialLite) to Revenj.AspNetCore 1.6.0
